#ifndef HEADER_H
#define HEADER_H

void absolute_value();
void vector_add();
void string_append();
void constructor();
void convert_string_to_number();
void convert_number_to_string();
void file_creation();
void file_read();
void file_read2();
void guessing_game();
void destructor();
void exceptions();
void hash_map_find();
void unordered_set();
void for_loop();
void random_run();
void random_gaussian_normal_dist();
void range_views();
void move_demo();
void heap();
void struct_fn();
void test_my_print();
int args_main(int argc, char* argv[]);
void member_functions();
void namespaces_aliases();
void nearest_integer();
void unordered_map();
void ordered_set();
void string_streams();
void csv_parsing();
void arrays();
void pointers();
void container_print();
void access_modifiers();
void recursion();
void remainder();
void smart_pointers();
void sort();
void string_split();
void square_root();
void square();
void unordered_map_custom_type();
void string_compare();
void string_length();
void ppm();
void substring();
void templates();
void string_trim();
void references();
void classes();

#endif
